### ISSUE TITLE
Kanban project board confirmation

### ISSUE THREAD

**Issue by danielochuba** [danielochuba/recipe-app#13]
https://github.com/danielochuba/recipe-app/projects/1

## Hello Reviewer were two Students here,
@danielochuba  and @JuanDBta

**Comment by OLIPLICHE** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Created Kanban board 👍 
- Created descriptive cards 👍 

## Required Changes ♻️
- Hi, in checking your task, I found out that two tasks from the requirements are missing in your Kanban: **1 Write unit and integration tests**, **2 Make sure there are no N+1 queries happening**.
**Can you add them because this should be among the tasks according to the requirements?**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by algerina** [comment]
Hi @team, 

You've done an amazing job on your Kanban board👏 💯 👍
There are some issues that you still need to work on to go to the next project but you are almost there! 

## Highlights
  -  Well done adding the unit and integration test tasks


## Required Changes ♻️

- [ ] Kindly as requested by the previous reviewer add a card for solving the N+1 queries.


Happy coding

**Comment by julie-ify** [comment]
Hi @danielochuba and @JuanDBta,

Good job so far!

## Highlights!
- Descriptive ISSUE✔️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] Kindly assign the task also. All tasks should be assigned accordingly.

  ![image](https://github.com/danielochuba/recipe-app/assets/81468675/2066a44a-daf9-4bb8-8818-26de48243a65)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif"/>
## Highlights
- Changes fixed ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
